version: '3'
services:
  frontend:
    image: cxy_frontend
    ports:
      - "80:80"
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: cxy_backend
    command: gunicorn -w 4 -k gevent cxy.wsgi -b 0.0.0.0:8000
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

